# Site wide configuration

title: Sztuka stenotypii
locale: pl_PL
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Krzysztof Smirnow
  #avatar: bio-photo.jpg
  #bio: "This is a sample Jekyll academic website."
  email: flamenco108@stenografia.pl
  # Do not include the @ symbol in your Twitter username
  #twitter: laderast
  #linkedin: #username
  #github: laderast
  #orcid: # ID Number (ex. 0000-0000-0000-0000)
  #researchgate: #username
  #mendeley: #username
  #google:
  #  plus: #username
  #  analytics:
  #  verify:
  #  scholar: #id
